### ISSUE TITLE
Sort on categories

### ISSUE THREAD

**Issue by apavlidi** [apavlidi/IT_API#36]
Sorting on categories by query on the URL does not seem to work properly.

**Comment by theokyr** [comment]
Using `GET /categories?sort=name` produces wrong results. This problem seems to be caused by MongoDB's sort which is case sensitive by default.

Most relevant information I've found while working on this:
- Using aggregation to dynamically create a case-insensitive version of `name` 
https://stackoverflow.com/a/22931481

- Case Insensitive Index (available in 3.4+)
https://docs.mongodb.com/manual/core/index-case-insensitive/

The already existing `value `field is already a case-insensitive version of the category name, albeit without any spaces. Using `GET /categories?sort=value` seems to yield more accurate results, but not perfect.

**Comment by apavlidi** [comment]
It seems that sorting works fine in the end.I think case sensitive sort is not a problem.Thank you @theokyr for your help :+1:
